[feat] blogs implemented
ariesiitr/Website-2.0 pull request #13
Opened 2023-10-07 11:42 UTC by riyaaaa123

fix #3

2023-10-07 12:01 UTC, pranav-iitr requested changes

2023-10-07 12:01 UTC, pranav-leo commented on backend/blog/models.py
> +    Web_image= models.ImageField(upload_to=get_blog_pics_path())
inconsit namming conv

2023-10-07 12:01 UTC, pranav-leo commented on backend/blog/views.py
> +from rest_framework.status import HTTP_200_OK, HTTP_204_NO_CONTENT
remove unused libraries

2023-10-07 12:01 UTC, pranav-leo commented on frontend/hooks/blogs.js
> +      errorCallback(err, "hi");
whom are sending hi to?

2023-10-07 12:01 UTC, pranav-leo commented on frontend/hooks/blogs.js
> +  if (!id) return Promise.reject("ID is not provided");
can remove this

2023-10-07 12:01 UTC, pranav-leo commented on frontend/package.json
> +    "test-all": "npm run check-format && npm run check-lint && npm run check-types && npm run build",
use yarn

2023-10-07 12:01 UTC, pranav-iitr commented on frontend/pages/blog/index.tsx
> +  const blogStyle = {
remove unused

2023-10-07 12:01 UTC, pranav-iitr commented on frontend/pages/blog/index.tsx
> +                style={{ background: "rgba(84, 84, 84,1)", color: "white" }}
use tailwind

2023-10-24 20:09 UTC, pranav-iitr approved these changes

2023-10-24 20:17 UTC, merged