Blog
ariesiitr/Website-2.0 pull request #7
Opened 2023-08-24 09:12 UTC by riyaaaa123

i made the blog frontend and backend

2023-08-24 11:49 UTC, pranav-iitr requested changes

2023-08-24 11:49 UTC, pranav-leo commented on backend/Aries/settings/common.py
> +        'blog.apps.BlogConfig',
put it in end where all apps are put

2023-08-24 11:49 UTC, pranav-leo commented on backend/blog/migrations/0001_initial.py
merge all the migrations into one

2023-08-24 11:49 UTC, pranav-leo commented on backend/blog/models.py
> +    @classmethod
remove trigram search from this file

2023-08-24 11:49 UTC, pranav-iitr commented on frontend/package.json
> +    "eslint": "^8.46.0",
remove ^ added in this page

2023-08-24 11:49 UTC, pranav-iitr commented on frontend/pages/blog/[id].tsx
> +    const styleObj = {
border radious jaise cheez ko tailwind use karo and rest ko common CSS file me daldo

2023-08-24 11:49 UTC, pranav-iitr commented on frontend/pages/blog/index.tsx
> +    // console.log("hihi")
remove unused comments

2023-08-24 11:49 UTC, pranav-iitr commented on frontend/pages/gallery/index.js
> +        backgroundBlendMode: "luminosity",
gallery ke liye nai branch banalo

2023-08-24 11:49 UTC, pranav-leo commented on frontend/utils/network.js
> +  return "http://localhost:8000";
isko env se read karo

2023-08-24 11:49 UTC, pranav-iitr commented on frontend/package-lock.json
remove this file

2023-08-24 11:49 UTC, pranav-iitr commented on frontend/hooks/blogs.js
> +      mutationKey: "get-auth-token",
mutation key sahi se daalo
and function name ache se likho

2023-08-24 11:49 UTC, pranav-iitr commented on backend/user/views.py
> +class TeamMemberView(ListCreateAPIView):
ApplicationBaseView ko kyu remove kiya ?

2023-08-24 11:49 UTC, pranav-leo commented on frontend/hooks/blogs.js
> +  const url= getUrl(`/blogs/trigram-search/?q=${encodeURIComponent(query)}`)
add query params use karo from network

2023-08-24 11:49 UTC, pranav-iitr commented on backend/utils/constants.py
> +    (1,'Verified'),
use classes

2023-08-24 11:49 UTC, pranav-iitr commented on backend/blog/models.py
> +    isverified= models.IntegerField(default=1,choices=Verification_choices)
postive integers use kar rahe ho to postive integers use karo

2023-08-24 11:49 UTC, pranav-iitr commented on backend/blog/models.py
> +class Blog(models.Model):
utils se json model and timestamp model use karo

2023-08-24 11:49 UTC, pranav-iitr commented on backend/Aries/settings/common.py
> +    CORS_ALLOWED_ORIGINS = [
CORS ki requierment nahi hai

2023-10-04 19:04 UTC, pranav-iitr requested changes

2023-10-04 19:04 UTC, pranav-leo commented on .env.local
Doesn't needs to be deleted

2023-10-04 19:04 UTC, pranav-leo commented on backend/Aries/settings/common.py
> -from configurations import Configuration
line is requiered

2023-10-04 19:04 UTC, pranav-leo commented on backend/Aries/settings/common.py
> +    # CACHE_MIDDLEWARE_ALIAS = 'default'  # The cache alias to use for storage and 'default' is **local-memory cache**.
remove these lines

2023-10-04 19:04 UTC, pranav-leo commented on backend/blog/urls.py
> +    # path('trigram-search/',trigram_search_view.as_view(), name='trigram_search'),
remove un used lines

2023-10-04 19:04 UTC, pranav-leo commented on backend/utils/constants.py
> +VERIFICATION_STATUS_CHOICES = (
will be a member of class

2023-10-04 19:04 UTC, pranav-iitr commented on frontend/pages/blog/[id].tsx
> +    console.log('Mutation successful!', res.data);
review console logs

2023-10-04 19:04 UTC, pranav-iitr commented on frontend/pages/blog/index.tsx
> +  const [searchText, setSearchText] = useState('');
type script ke formats sahi se use karo

2023-10-04 19:04 UTC, pranav-iitr commented on frontend/pages/gallery/index.js
> +import React , { useState } from 'react'
remove code for gallery

2023-10-04 19:04 UTC, pranav-iitr commented on frontend/utils/network.js
> +  // if (env == 'production') return process.env.PRODUCTION_SERVER;
read these form env

2023-10-07 13:32 UTC, closed without merging